default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hello-rails-react_development

test:
  <<: *default
  database: hello-rails-react_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: hello-rails-react_production
  username: hello-rails-react
  password: <%= ENV['HELLO_RAILS_REACT_DATABASE_PASSWORD'] %>
